### ISSUE TITLE
precision of the baseline model

### ISSUE THREAD

**Issue by wenhe-jia** [MinghanLi/BoxVIS#1]
Thank you for your excellent work!
In your paper, the mentioned fully-supervised Mask2Former model for performance comparing achieves 43.2 mAP on YouTube-VIS-2021 validation subset. I tried to reproduce this baseline according to the cues from both the paper and the repository of yours, but I still get around 40.6 mAP as reported in the original Mask2Former paper.

I set the following training configs:
```
    cfg.INPUT.SAMPLING_FRAME_NUM = 3
    cfg.INPUT.SAMPLING_FRAME_RANGE = 10
    cfg.INPUT.MIN_SIZE_TRAIN = (320, 352, 384, 416, 448, 480, 512)
    cfg.SOLVER.IMS_PER_BATCH = 16
    cfg.SOLVER.BASE_LR = 0.0001
    cfg.SOLVER.STEPS = (12000,)
    cfg.SOLVER.MAX_ITER = 15000
    cfg.DATASETS.TRAIN: ("ytvis_2021_train", )
    cfg.DATASETS.TEST: ("ytvis_2021_val", )
```
Can you tell me how I can reproduce the fully-supervised Mask2Former precision of 43.2 mAP?

**Comment by MinghanLi** [comment]
Actually, M2f-VIS does not use any tracker to associate objects across frames. During inference, when we introduce the frame-level tracker proposed in MinVIS into M2F-VIS, the performance increase from 40.6 to 43.1 mAP. 

So, you do not need to re-train M2F-VIS, just need to introduce the tracker by query embedding similarity.
